gost-engine/engine

gost_eng.c

ERR_load_GOST_strings() is called from bind_gost but there is no corresponding call to ERR_unload_GOST_strings() in gost_engine_destroy.
This is a fairly minor issue but should probably be fixed.

Fix missing cleanup of GOST specific error messages

---

CMakeLists.txt

The GOST engine is a dynamically loadable module rather than a shared
library, so make that explicit.  However, the programs gost12sum,
gostsum nd gostsum12 need to link against the algorithms implemented
as part of the engine, so separate those out into a static library
that both programs and engine link with.
This also renames the GOST engine to conform better to OpenSSL >=1.1.0 standards

Separate GOST engine and GOST library, make GOST engine a module

---

CMakeLists.txt
CMake_ReadMe.md

It really already was, this only removes artifacts in CMakeLists.txt

Make gost-engine independent of OpenSSL SOURCE

---

CMakeLists.txt
gost12sum.c
gost_ameth.c
gost_ec_keyx.c
gost_grasshopper_cipher.c

Successfully tested with Clang-4.0, Clang from Xcode-8.3.3, GCC_6.3.0. Under cmake-3.8.2.
1. Fix compiler warnings. Only `gost_grasshopper_precompiled.c` still generates plenty of warnings.
2. Enabled build using GCC or Clang - cmake feeds the correct parameters automatically.

Address compiler warnings and build with CMAKE_C_FLAGS

---

gost_grasshopper_cipher.c

Allow double calling of gost_grasshopper_cipher_cleanup(), and some sanity checking for cipher type value.
Первый if устраняет некотоыре краши в openvpn.

Sanity checking in gost_grasshopper_cipher_cleanup

---

.travis.yml

CMakeLists.txt uses `add_test` to execute `test/run_tests` which does the same thing as the `prove` line did.

Use `make test` to run tests

---

CMakeLists.txt
benchmark/sign.c

- Cycle through all supported parameters.
- Also do verification tests.
- Increase precision of timer (allow test to work faster).
ps. Я бы оставил бенчмарк в общей дире.

benchmark: Extend sign/verify benchmark.

---

CMakeLists.txt
test/run_tests

If OPENSSL_ROOT_DIR is specified pass it to the perl tests, and set its
value as LD_LIBRARY_PATH, if unset. This allows to run tests for custom
openssl build without manually setting proper env.

run_tests: pass OPENSSL_ROOT_DIR into perl tests

---

gost_eng.c
gost_lcl.h
test_params.c

- Убрал вызов `fill_GOST_EC_params` и `bind_gost`.
- Дополнительные тесты.

 test_params: remove calls to internall API and add more tests

---

gost_pmeth.c

Very simple redirect to EC_KEY_check_key() which is doing all basic
checks (see crypto/ec/ec_key.c:ec_key_simple_check_key()).
Resolves #44

Implement EVP_PKEY_{,public_}check

---

test_curves.c
test_params.c
test_sign.c

In preparation for memory leak detector fix them in the tests.
Add forgotten comparison in test_curves.

Fix leaks in tests

---

CMakeLists.txt

Test if clock_gettime() requires linking with -lrt and link sign
benchmark with rt if needed. clock_gettime() requires -lrt only for
glibc versions before 2.17.

cmake: benchmark/sign - link with rt for clock_gettime when needed

---

CMakeLists.txt
test_curves.c
test_params.c
test_sign.c

Define ENGINE_DIR for all binary tests. Instead of auto-loading engine
using `example.conf' load it directly from the OUTPUT_DIRECTORY for
curves tests.

tests: Load just built engine from the output directory

---

.travis.yml
test/00-engine.t
test/01-digest.t
test/02-mac.t
test/03-encrypt.t
test/04-pkey.t

At least Fedora 30 will have no Test::More anymore. Test::More is
deprecated, as well as Test::Stream and Test2 is a recommended
replacement.
Luckily, gost-engine's use of Test::More is limited to functions which
are compatible with implementations in Test2, so only module import and
test plan announcement need to change.

Migrate test framework to Test2

---

test_tls.c

Otherwise `struct sockaddr_in` is undefined for test_tls.
Reported in #123 by f-andrey.

Fix compilation on FreeBSD

---

.travis.yml

after https://github.com/openssl/openssl/pull/8951

travis-ci: cleanup "so/dylib" mangling, not needed

---

.travis.yml
test_grasshopper.c
test_keyexpimp.c

Make proper engine initialization for tests instead of
EVP_add_cipher/EVP_add_digest hack. Fixes #151.

Fix test_grasshopper and test_keyexpimp engine init

---

gost_pmeth.c

The second argument for the pkey_copy function has been constified in
OpenSSL to be 3.0.  This is normally not a problem, but when passing a
pointer to such a function, the compiler does complain.
This change solves the issue by looking at the macros
OPENSSL_VERSION_MAJOR, which is new in OpenSSL to be 3.0, and set
constness based on that.
Fixes #154

gost_pmeth.c: mitigate for constness difference in copy function

---

.cirrus.yml
test/run_tests

When the environment variable OPENSSL_ROOT_DIR is defined, we need to
ensure that PATH and LD_LIBRARY_PATH are properly affected.
This is a little bit complicated, since OPENSSL_ROOT_DIR could point
at an OpenSSL build directory as well as an OpenSSL installation
tree.  Fortunately, it's easy to detect the difference; if it's a
build tree, there's a sub-directory 'apps'.
For installation trees, it's further complicated by OpenSSL's
'multilib' target attribute, which exists for platforms that support
directory separated libraries for differing bitness (typically 32-bit
and 64-bit libraries).  We trust pkg-config to give us the answer.
Binaries are easier, they live in $OPENSL_ROOT_DIR/bin.
Fixes #146

test/run_tests: Always set paths when OPENSSL_ROOT_DIR is defined

---

test/run_tests

Not all systems recognise LD_LIBRARY_PATH, and we therefore need to
set other environment variables.
Currently set:
- LD_LIBRARY_PATH (Linux and ELF HP-UX)
- DYLD_LIBRARY_PATH (MacOS X)
- LIBPATH (AIX, OS/2)
More can be added as the need arises.
Fixes #146

test/run_tests: extend support for more operating systems

---

CMakeLists.txt
test/00-engine.t
test/01-digest.t
test/02-mac.t
test/03-encrypt.t
test/04-pkey.t

Have CMakeLists.txt specify a value for the env var `OPENSSL_CONF`.  This will ensure a value from the user's environment won't cause trouble with the tests.  Also, don't set `OPENSSL_ENGINES` in the .t scripts, and especially not to a bogus value.

Cleanup tests

---

gost_omac.c
gost_omac_acpkm.c
test_grasshopper.c

XOF (eXtendable-Output Function) is supported in OpenSSL since version
1.1.1.  Unfortunately, that support is limited, as it requires calling
EVP_DigestFinalXOF().  However, the grasshopper code wasn't compatible.
This changeset adds XOF support in grasshopper
This changeset removes the _meth_ calls from test_grasshopper.c (they
should never have been there, but considering support for XOF came so
late in OpenSSL, their presence is understandable) and uses supported
functionality for this sort of thing instead.

For Grasshopper OMAC_ACPKM, OMAC and MAGMA, support XOF

---

gost_ec_keyx.c
test_grasshopper.c

test_grasshopper: Fix CIDs 253281, 253280, 253279, 253275
gost_ec_keyx: Fix CID 253283 Unchecked return value in VKO_compute_key

Fixes for Scan 20190918

---

gost_ameth.c

Исправил утечки которые описаны в #179.
Для algobj вызов делать не нужно.
Заметил что не проверялось выделение octet, до него тоже дописал проверку.

Fix leaks in priv_encode_gost()

---

gost_ameth.c

Even though it is not recommended by R 1323565.1.023-2018 fill
digestParamSet field for 512-bit curves Test, TC26-A, TC26-B because old
cryptoproviders expect this field to be present.
Signed-off-by: Dmitry Eremin-Solenikov <dbaryshkov@gmail.com>

ameth: fill digestParamSet for the sake of backwards compatibility

---

.travis.yml

master branch of parent OpenSSL project switched to 3.x version. To pass travis tests OpenSSL GOST engine require OpenSSL version 1.1.1.

fix .travis.yml. make test against openssl-stable 1.1.1   

---

CMakeLists.txt

Following commits mark CMAC and HMAC primitives deprecated:
commit a6d572e60120e0ffb42aece17a085f0fed1b8f6f
Author: Pauli <paul.dale@oracle.com>
Date:   Tue Jan 14 10:59:11 2020 +1000
Deprecate the low level CMAC functions
commit dbde4726889a19af0a718fe9c5542f39c81acbd3
Author: Pauli <paul.dale@oracle.com>
Date:   Tue Jan 14 12:11:50 2020 +1000
Deprecate the low level HMAC functions
Add `-Wno-error=deprecated-declarations' to appropriate targets.
References:
https://github.com/openssl/openssl/commit/a6d572e601
https://github.com/openssl/openssl/commit/dbde472688

CMakeLists.txt: Workaround openssl deprecation of HMAC and CMAC primitives

---

gost89.c
gost_crypt.c

Removes unset local buffer meshing. This removes valgrind errors.

Remove unset local buffer meshing. This removes valgrind errors.

---

.travis.yml

* 794ec44 travis-ci: Always describe openssl branch
- Отображение commit id, так как `master` может менять от времени. Чтоб было ясно какой именно master был на момент запуска тестов.
* ae8f2c6 travis-ci: Add clang build for linux/x86_64/openssl-master
- clang без OSX. Так как OSX может вносить свои ошибки, а интерсно проверить clang без них.
* d7e7c64 travis-ci: Add (big-endian) s390x build
- Big-endian arch.
* 0e7e5ea travis-ci: Speed-up openssl build
- Не собирать man pages.
* 984f50b travis-ci: Add 32-bit build (i386)
- 32-bit arch.

.travis.yml improvements

---

gosthash2012.c
gosthash2012.h
gosthash2012_ref.h
gosthash2012_sse2.h

Пример PR для @ddulesov из #198. Изменения разбиты на мелкие смысловые части. SIMD и `_addcarry_u64` изменений я не добавлял. Список коммитов:
* gosthash2012: Optimize out temporary `buf' from `stage3'
* gosthash2012: Optimize `gost2012_hash_block' loop
* gosthash2012: Change some byte (pointers) to union uint512_u
* gosthash2012: Remove temporary variable from `stage2'
* gosthash2012: Make `add512' to work in-place
* gosthash2012: Simplify `pad'
* gosthash2012: Remove redundant `memset' form `init_gost2012_hash_ctx'
* gosthash2012: Remove redundant `hash' field from `struct gost2012_hash_ctx'
Там есть немного моих изменений:
* gosthash2012: Remove unreachable code from `pad'
* gosthash2012: Simpler version of add512
Кроме этих двух коммитов везде автором указан dmitry dulesov. Раз уж я …

PR example of Dulesov Streebog optimizations

---

.travis.yml

* Fixes: cb1b5ff ("travis-ci: Speed-up openssl build")
-- В OpenSSL_1_1_1-stable нет build_sw, который использовался в том коммите.
* Remove redundant 'os: linux', 'compiler: gcc' tags.
-- Это умолчания, чтоб не загромождать конфиг.
* Order jobs: x86_64 builds, analysers, other arches, other OSes.
-- Было вперемешку разные архитектуры и т.п. Сейчас сделал сначала сборки на x86_64, как основная архитектура, потом остальное.
* Build all jobs against 'OpenSSL_1_1_1-stable' by default.
* Mark openssl-master build as 'allow_failures' for PRs.
-- То о чем говорилось в этом обсуждении https://github.com/gost-engine/engine/issues/198#issuecomment-581158581
** Все собирается с OpenSSL_1_1_1-stable, кроме однйо сборки с openss/master
** Эта сборка с мастер в пулл реквестах отмечена как …

Travis: Fix and optimize .travis.yml again

---

CMakeLists.txt
gosthash2012.c
gosthash2012_ref.h

* Добавил в cmake тест наличия рабочего `_addcarry_u64`
* Небольшая оптимизация XLPS для `-ref` имплементации.
То о чём говорилось в #206.

Streebog: _addcarry_u64 test and XLPS optimizations for ref code

---

gosthash2012_sse2.h

Не только не используется, но и содержит интринсик от SSE4.1.

streebog: Remove unused __EXTRACT64 macro

---

gosthash2012.c

`_mm_empty' is not needed on x86_64, because we only using SSE2.
But, I didn't notice that EXTRACT32 (32-bit version of EXTRACT) is
using MMX registers and intrinsics, so complete removing of
`_mm_empty' (EMMS) was mistake.
Make it presence conditional only for IA-32.
Fixes: 211489f ("gosthash2012: Improve SIMD implementation")
Предыдущее обсуждение: https://github.com/gost-engine/engine/pull/206#issuecomment-582853071
Я не смог удалить MMX код без замедления, поэтому пока просто возвращаю `_mm_empty`.
Заодно добавил комментарий, чтоб в следующий раз не забыли про это.

gosthash2012: Issue EMMS on 32-bit SIMD implementation

---

CMakeLists.txt

`Test2::V0' is non standard and rarely present on systems, making `make
test' unnecessarily fail.

CMakeLists.txt: Skip perl tests if there is no Test2::V0

---

gost89.c
gost_ameth.c
gost_crypt.c
gost_ec_keyx.c
gost_ec_sign.c
gost_grasshopper_cipher.c
gost_lcl.h

OpenSSL suggests to use (and internally itself uses)
`BN_{CTX_,}secure_new' primitives to work with private keys.
These are using `OPENSSL_secure_malloc' et al. calls, which use
special 'secure heap' memory.
https://www.openssl.org/docs/manmaster/man3/OPENSSL_secure_malloc.html
Надеюсь, нигде не пропустил.

ec: Use BN_{CTX_,}secure_new memory API for priv keys

---

test/04-pkey.t

* Tests that gost-engine correctly computes the public key from the private key. (Twice -- Alice and Bob.)
* Tests that gost-engine correctly computes the derived shared key. (Twice -- Alice and Bob, should be identical.)
These vectors are "golden" in the sense they were generated "out-of-band". The ECC computations were done by `python-fastecdsa` and hashing by `python-pygost`. I used `openssl asn1parse` to embed the ECC results into PEMs.
Comments warmly welcome -- I haven't used perl since the late 90s :see_no_evil: 
Tagging @beldmit

[test] ECC: KATs for the curves in RFC4357 and RFC7836

---

gost_crypt.c
test_ciphers.c
test_digest.c

```
test_ciphers: Enable Magma CBC test
gost_crypt: Fix Magma CBC in-place decryption
test_digest: Add another carry test vector, also test GOST94
test_digest: Reduce arguments to tests, make concise logging
test_digest: Test CMAC using EVP_MAC (provider) API
test_digest: Test old and new APIs
test: List untested digests and ciphers
```

Misc test improvements + Fix Magma CBC

---

gost_crypt.c
gost_eng.c
gost_grasshopper_cipher.c
gost_keyexpimp.c
gost_lcl.h

Register cipers using definition tables. Introduce `GOST_cipher` type.
o gost_eng: Rework (simplify) cipher registration
o gost_keyexpimp: Rework cipher registration
o gost_grasshopper_cipher: Remove redundant code
o gost_grasshopper_cipher: Rework cipher registration
o gost_crypt: Allow templates in GOST_cipher
o gost_crypt: Add magma_cbc_cipher
o gost_crypt: Add magma_ctr_acpkm_omac_cipher
o gost_crypt: Add magma_ctr_acpkm_cipher
o gost_crypt: Add magma_ctr_cipher
o gost_crypt: Add Gost28147_89_cnt_12_cipher
o gost_crypt: Add Gost28147_89_cnt_cipher
o gost_crypt: Add Gost28147_89_cbc_cipher
o gost_crypt: Rework cipher registration, add Gost28147_89_cipher

Rework ciphers registrtion

---

gost_crypt.c
gost_eng.c
gost_grasshopper_cipher.c
gost_grasshopper_cipher.h
gost_keyexpimp.c
gost_lcl.h
gost_md.c
gost_md2012.c
gost_omac.c
gost_omac_acpkm.c

o gost_eng: Simplify digest registration
o gost_md: Rework alias support in digest registration
o gost_omac_acpkm: Rework registration of kuznyechik_ctracpkm_omac
o gost_omac: Rework registration of magma/kuznyechik OMAC digests
o gost_md2012: Add registration using GostR3411_2012_{256,512}_digest
o gost_crypt: Add Gost28147_89_MAC_digest, Gost28147_89_mac_12_digest
o gost_md: Rework digest registration, add GostR3411_94_digest

Rework digest registrations using table method

---

.travis.yml

Such as, no need to run tests if build failed.

.travis.yml: Make Travis script fail early

---

benchmark/sign.c

Bug found by Clang scan-build.
Fixes #258.

benchmark/sign: Fix crash on incorrect options

---

test_digest.c

Script based renaming:
```SH
sed -i -e 's/EVP_MAC_CTX_new/EVP_MAC_new_ctx/g'               \
-e 's/EVP_MAC_CTX_free/EVP_MAC_free_ctx/g'             \
-e 's/EVP_MAC_CTX_dup/EVP_MAC_dup_ctx/g'               \
-e 's/EVP_MAC_CTX_mac/EVP_MAC_get_ctx_mac/g'           \
-e 's/EVP_MAC_CTX_get_params/EVP_MAC_get_ctx_params/g' \
-e 's/EVP_MAC_CTX_set_params/EVP_MAC_set_ctx_params/g' \
`egrep -rl 'EVP_MAC_CTX_new|EVP_MAC_CTX_free|EVP_MAC_CTX_dup|EVP_MAC_CTX_mac|EVP_MAC_CTX_get_params|EVP_MAC_CTX_set_params'`
```

EVP_MAC: APIs were renamed so they need to be fixed in here too.

---

CMakeLists.txt
gost_ec_keyx.c
gost_lcl.h
gost_pmeth.c
test_derive.c

Ещё не готово, но уже выдает ошибку для VKO_GOSTR3410_2012_512.
~~~
$ bin/test_vko
Test R 50.1.113-2016 A.9 (p.18) gost2012_256
Public key a4edb0aa matches private key d9ec90c9
Public key 83e12f19 matches private key f759c848
EVP_PKEY_get_default_digest_nid 983
0000 - c9 a9 a7 73 20 e2 cc 55-9e d7 2d ce 6f 47 e2 19   ...s ..U..-.oG..
0010 - 2c ce a9 5f a6 48 67 05-82 c0 54 c0 ef 36 c2 21   ,.._.Hg...T..6.!
KEK match
Test R 50.1.113-2016 A.10 (p.19) gost2012_512
Public key a4edb0aa matches private key d9ec90c9
Public key 83e12f19 matches private key f759c848
EVP_PKEY_get_default_digest_nid 983
0000 - c9 a9 a7 73 20 e2 cc 55-9e d7 2d ce 6f 47 e2 19   ...s ..U..-.oG..
0010 - 2c ce a9 5f a6 48 67 05-82 c0 54 c0 ef 36 c2 21   ,.._.Hg...T..6.!
KEK mismatch
= Some tests FAILED!
$
~~~
Пока не …

test_vko: Add VKO tests from R 50.1.113-2016

---

ecp_id_GostR3410_2001_CryptoPro_A_ParamSet.c
ecp_id_GostR3410_2001_CryptoPro_B_ParamSet.c
ecp_id_GostR3410_2001_CryptoPro_C_ParamSet.c
ecp_id_GostR3410_2001_TestParamSet.c
ecp_id_tc26_gost_3410_2012_256_paramSetA.c
ecp_id_tc26_gost_3410_2012_512_paramSetA.c
ecp_id_tc26_gost_3410_2012_512_paramSetB.c
ecp_id_tc26_gost_3410_2012_512_paramSetC.c

`char` defaults to signed on x86/x64, but unsigned on ARM.
The ECCKiila unit tests were failing pretty much across the board. Our CI is x64 -- it was actually OpenSSL's CI that picked this up.
@luinxz found and fixed the ECCKiila defect (thanks!). This PR is just the resulting template changes.

GOST EC armv7 aarch64 fixes

---

ecp_id_tc26_gost_3410_2012_256_paramSetA.c
ecp_id_tc26_gost_3410_2012_512_paramSetC.c

ECCKiila Changes from
https://gitlab.com/nisec/ecckiila/-/issues/2
https://gitlab.com/nisec/ecckiila/-/commit/7445ecabef77965743e0ae8d39d7433b07820be6
* X3 -> X1
* eliminate a temp variable
X3 = X1 as pointers is the reason this was still passing unit tests.
But that might not hold in future versions of ECCKiila, so fix it now.

Edwards map fix

---

CMakeLists.txt

This is based on AX_CHECK_ALIGNED_ACCESS_REQUIRED from autoconf-archive.
Note, that on some arches unaligned access behavior could be changed at
runtime via prctl(1). Also, unaligned memory access is still slower (and
very slow on some arches) even if it's not strictly required.
Можно для чего-нибудь использовать, если нужно.

Provide cmake test if alignment requirement is strict

---

gost89.c
gost89.h

In gost94 digest every step set 4 temporary keys for gost89 with mask, but mask is needless here, there is not a real cipher key.  RAND_priv_bytes drops the performance.
With RAND_priv_bytes calls in digest:
$ time bin/gostsum ../../10M.bin
52a8d8b81c9da69da38500ddcbc3374341f8bf158e7531879eba8c8c199cea5b ../../10M.bin
real    0m3,353s
user    0m2,830s
sys     0m0,480s
Without RAND_priv_bytes calls in digest:
$ time bin/gostsum ../../10M.bin 
52a8d8b81c9da69da38500ddcbc3374341f8bf158e7531879eba8c8c199cea5b ../../10M.bin
real    0m0,530s
user    0m0,504s
sys     0m0,000s

disable gost key mask on gost94 digest steps due to performance issues

---

CMakeLists.txt

/root/rpmbuild/BUILD/openssl-gost-engine-1.1.1/CMakeFiles/CMakeTmp/src.c:4:14: warning: initialization of 'int *' from incompatible pointer type 'char *' [-Wincompatible-pointer-types]
4 |     int *p = buf + 1;
|              ^~~
/root/rpmbuild/BUILD/openssl-gost-engine-1.1.1/CMakeFiles/CMakeTmp/src.c:5:14: warning: initialization of 'int *' from incompatible pointer type 'char *' [-Wincompatible-pointer-types]
5 |     int *q = buf + 2;
|              ^~~
Reported-by: Ilya Shipitsin <https://github.com/chipitsine>
Fixes: #288

CMakeLists.txt: Fix warning on gcc-9

---

gost89.c
gost89.h
gost_crypt.c
gost_grasshopper_cipher.c
gost_lcl.h

implement EVP_CTRL_TLSTREE case for magma & kuznechik ctrl function.
some minor changes for storing master key in magma cipher, used for TLSTREE mode.

ctrl function implementation for magma & kuznechik

---

gost_ameth.c
gost_ec_keyx.c
gost_eng.c
gost_pmeth.c

Superseeds https://github.com/gost-engine/engine/pull/297
Этот патч позволяет в Линуксе использовать PKCS#12 контейнеры, созданные с помощью ViPNet CSP под Windows.
Я могу приложить тестовый контейнер, который был создан следующим образом:
Получен тестовый сертификат по инструкции http://testcert.infotecs.ru/help.html
Полученный тестовый сертификат установлен в Windows
Штатными средствами ViPNet в Windows контнейнер с сертификатом экспортированы в PKCS#12 блоб.
Поведение до:
$ openssl pkcs12 -engine gost -info -in test_vipnet.pfx
engine "gost" set.
Enter Import Password:
MAC: GOST R 34.11-94, Iteration 2000
MAC length: 32, salt length: 32
PKCS7 Data
Shrouded Keybag: PBES2, PBKDF2, gost89, Iteration 2000, PRF id-HMACGostR3411-94
Error outputting keys and certificates …

Add explicit support for NID_id_GostR3410_2001DH (GOST R 34.10-2001 DH)

---

gost_crypt.c

If at the input of the encryption function in the CFB mode we have
an integer number of blocks, then in the main loop all blocks will be
processed, except for the last one due to an incorrect border check.
The last block will be fully processed as a "partial" remainder, but
the initialization vector will not be updated. And, thus, the value
of IV will always be incorrect in this case.
This breaks stateless protocols due to an invalid initialization vector:
all messages except the first cannot be decrypted. (Naturally, we are
talking about a case with disabled key meshing, which does not allow
context recovery due to an erroneous implementation.)
It is worth noting here that the code for processing partial blocks
(both at the input of the encryption functions and at the output) is
a …

Fix broken initialization vector, make stateless protocols happy

---

gost_crypt.c

changed const NID_magma_ctr_acpkm to NID_id_tc26_cipher_gostr3412_2015_magma_ctracpkm
changed const NID_magma_ctr_acpkm_omac to NID_id_tc26_cipher_gostr3412_2015_magma_ctracpkm_omac
build errors are gone

NID_magma_ctr_acpkm consts changed (#304)

---

CMakeLists.txt
gost_ctl.c
gost_eng.c

GOST_CORE_SOURCE_FILES and GOST_ENGINE_SOURCE_FILES were a bit
disorganised, they are now re-arranged so GOST_ENGINE_SOURCE_FILES
contains ENGINE specific source only, and what was less ENGINE
specific was moved to GOST_CORE_SOURCE_FILES.  Furthermore,
GOST_LIB_SOURCE_FILES now includes GOST_CORE_SOURCE_FILES, so the
gost_core library is complete with all implementations.
As a consequence, 'gost' is now explicitly made into a dlopenable
module.  On some operating systems, that makes a difference.
This paves the way for alternative implementations based on the same
base code, such as a provider implementation.
It's quite possible that the re-arrangement done here isn't "pure"
enough.  Future development will tell.

Cleanup source organisation, and make 'gost' an actual module

---

.github/workflows/ci.yml
CMakeLists.txt

On MacOS X, OpenSSL and cmake have different ideas on what suffix a
dynamically loadable module should have.  OpenSSL expects .dylib,
while cmake uses .so by default.
Fixed by explicitly telling cmake to use the same suffix as for shared
libraries.

Fix gost engine suffix (for MacOS X)

---

CMakeLists.txt
gost-engine.h
gost_eng.c

In this form, the GOST engine isn't loadable through OpenSSL's dynamic
ENGINE loader, but directly as its own function, ENGINE_load_gost().
After making that call, the engine functionality can be used as usual.
This also rearranges the code in gost_eng.c, as the binding
functionality was spread around in the file.  Now, it's all nicely
tucked at the end.

Also build gost-engine in library form

---

test_ciphers.c
test_context.c
test_curves.c
test_derive.c
test_digest.c
test_params.c
test_sign.c

Using cNORM after "\n" may or may not work, probably because of the
line buffered nature of standard output.
If an error is displayed immediately after a printf that has cNORM
after "\n", the error output sometimes "overrides" the cNORM, and you
may end up with a surprisingly colorful error message, not to mention
that this may also affect your prompt in the same manner.
The lesson is to always output cNORM before the ending "\n".

Always cNORM before "\n"

---

CMakeLists.txt

Fixes issue #322. Make CMakeLists.txt compatible with cmake lower than 3.14, explicitly specify target destination paths.

Fix #322: make CMakeLists.txt compatible with cmake versions lower than 3.14

---

.github/workflows/codeql-analysis.yml

From 3.0.0-alpha6 to 3.0.0-alpha13, mostly for Analysis to avoid
getting failures when compiling, considering that the GOST source has
adapted for the latter version.

.github/workflows/codeql-analysis.yml: Bump the OpenSSL version

---

CMakeLists.txt

Cmake doesn't support the variable CMAKE_INSTALL_DIR.  However, with
the GNUInstallDirs module, there is the variable CMAKE_INSTALL_MANDIR.

Install manuals in the correct location

---

CMakeLists.txt
tcl_tests/dgst.try
tcl_tests/enc.try
tcl_tests/mac.try
tcl_tests/ossltest.tcl
tcl_tests/runtest.sh

When building in a directory that's separate from the source
directory, test results should end up in the build directory, not the
source directory.
Essentially, unless you do build in the source directory, it should be
regarded as read-only when building.

Don't put test results or intermediary files in the source tree

---

CMakeLists.txt
test/engine.cnf
test_ciphers.c
test_context.c
test_curves.c
test_derive.c
test_digest.c
test_params.c
test_sign.c
test_tls.c

The following programs had a hard coded load of the gost engine.
This changes them to rely more on the testing environment, and to
load engines through configuration files.
This affects: test_ciphers.c, test_context.c, test_derive.c,
test_digest.c, test_params.c, test_sign.c, test_tls.c

Make test programs less hard-coded

---

CMakeLists.txt

These days, the OpenSSL cmake package finder is capable of finding
a custom OpenSSL installation with no OPENSSL_ROOT_DIR defined, but
CMAKE_PREFIX_PATH defined.
However, gost-engine's CMakeLists.txt does use OPENSSL_ROOT_DIR, so
it needs it to be defined unconditionally.  That's arranged fairly
easily by assigning it the parent directory of OPENSSL_INCLUDE_DIR.

Set OPENSSL_ROOT_DIR if it isn't set.

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml

Most of all, at least openssl-3.0.0-alpha16 is needed, because there
are API changes made in that release that affects gost-engine builds

Update the OpenSSL 3.0 tag to openssl-3.0.0-alpha17

---

ecp_id_tc26_gost_3410_2012_256_paramSetA.c
ecp_id_tc26_gost_3410_2012_512_paramSetC.c
gost_ec_keyx.c
test/04-pkey.t

Relates to [this ECCKiila issue](https://gitlab.com/nisec/ecckiila/-/issues/3).
@beldmit when you wrote
> is the current code in the GOST engine correct here? The KAT should be very useful, if possible
and I said it was fine, I was wrong :\ Sorry. I misread the rigging -- it was the OpenSSL rigging, not the GOST Engine rigging.
Anyway, here's the fix, and two KATs. If you apply only 41e89a6 to master, you should see the one failure. The 512-bit curve wasn't affected here, because ord(G) is slightly smaller than a power of two, in contrast to the 256-bit curve with ord(G) slightly larger than a power of two. In this regard, the `id_tc26_gost_3410_2012_256_paramSetA` parameters are slightly sub-optimal.
At least it wasn't a silent error, and the engine caught it when packing the BIGNUM to …

push VKO cofactor clearing into ECCKiila

---

CMakeLists.txt

The static OpenSSL libraries have some dependencies that need to be
recorded fofr everything that's linked against it.  To achieve this,
we use ${OPENSSL_CRYPTO_LIBRARIES} and ${OPENSSL_SSL_LIBRARIES}
instead of ${OPENSSL_CRYPTO_LIBRARY} and ${OPENSSL_SSL_LIBRARY}.
Cmake is generally good at tracking specified dependencies between
libraries.  All that we need to do is to establish a dependency on
OpenSSL's libcrypto for 'gost_core', and then we can reduce the amount
of repeated dependencies for everything that links against 'gost_core'.
Cmake 3.0 was a switch to using targets and properties rather than
variables when linking different components together.
We follow that philosophy by dropping ${OPENSSL_CRYPTO_LIBRARIES} and
${OPENSSL_SSL_LIBRARIES} in favor of OpenSSL::Crypto and …

Reduce cmake dependency info

---

.editorconfig
.github/workflows/windows.yml
CMakeLists.txt
gost12sum.c
gost_crypt.c
gost_grasshopper_cipher.c
gost_keyexpimp.c
gost_md.c
gost_omac.c
gost_pmeth.c
gost_prov.c
gost_prov_cipher.c
gost_prov_digest.c
gosthash2012_ref.h
gosthash2012_sse2.h
test_ciphers.c
test_context.c
test_curves.c
test_derive.c
test_digest.c
test_gost2814789.c
test_gost89.c
test_keyexpimp.c
test_params.c
test_sign.c
test_tls.c
test_tlstree.c

Правда куча ошибок при сборке. Гораздо больше чем тут https://github.com/gost-engine/engine/issues/370
Может я как-то не так собрал openssl.

CI: Build on Windows

---

CMakeLists.txt

To maintain backward compatibility for users already familiar with older engine
build type (basically restores `-O2 -g').
Based on: https://blog.kitware.com/cmake-and-the-default-build-type/
Back reference: https://github.com/gost-engine/engine/pull/332#issuecomment-994160305

CMake: Set default build type to RelWithDebInfo

---

.github/workflows/windows.yml
CMakeLists.txt
test_tls.c

Rework the test to be similar to sslapitest.c. Using BIO only connections
and non-blocking IO instead of socketpair and separate processes.
This will allow it to compile and work on Windows.
Thus, re-enable test on Windows.

test_tls: Rework test to be single process

---

gost_ec_keyx.c
gost_prov.c

Fix 2 of 3 issues found by Coverity in #380:
- In `pkey_gost2018_decrypt` rearranged NULL pointer checks.
- `PROV_CTX` malloc in `gost_prov.c`:::`provider_ctx_new` (JFYI @levitte).

Fix 2 issues found by Coverity

---

gost_crypt.c
gost_grasshopper_cipher.c
gost_lcl.h

add case 'EVP_CTRL_TLSTREE' in ctl function for magma and kuznetchik.
add some GOST tests in tlstree test.
remove OpenSSL3.0 dependencies.
modify gost cipher to store master key, used for TLSTREE mode.
remove projects, that depend on OpenSSL3.0.
add options to remove compiler 'const' errors.

add magma and kuznetchik support for TLSTREE mode

---

test_sign.c

GCC do not understand that `algname` cannot be NULL. Add dummy default case to
cover all execution paths.
Fixes https://github.com/gost-engine/engine/issues/389

Fix gcc12 -fanalyzer warning

---

gost_ec_sign.c

Ensure 0 < r < q, 0 < s < q. (34.10-2021 6.2).

gost_ec_sign: Fix sig verify step 1 range checks

---

patches/openssl_111r.diff

This PR improve openssl trace output (commands 's_client'/'s_server' with '-trace' option). Some gost cipher suites and signature algorithms outputs as ''UNKNOWN'. See output example below.
This is true for new added TLS1.3 cipher suites and signature algorithms.
example output (s_client '-trace -ciphersuites TLS_GOSTR341112_256_WITH_MAGMA_MGM_L -curves GC256A'):
```
Sent Record
Header:
Version = TLS 1.0 (0x301)
Content Type = Handshake (22)
Length = 342
ClientHello, Length=338
client_version=0x303 (TLS 1.2)
Random:
...
session_id (len=32): AFB80D71BE56675B2FF7460129AD64875D02C3EA23A61D43120B02D1439C8CEC
cipher_suites (len=68)
{0xC1, 0x04} UNKNOWN
...
compression_methods (len=1)
...
extensions, length = 197
extension_type=ec_point_formats(11), length=4
... …
```

patches: improve SSL_trace output

---

CMakeLists.txt

install(EXPORT GostEngineConfig DESTINATION share/cmake/GostEngine) will to a path like this: /usr/GostEngine/share/cmake/GostEngine/GostEngineConfig.cmake which is not standard or expected. These files should be installed to: /usr/share/cmake/GostEngine/GostEngineConfig.cmake which can be done by changing the installation line to: install(EXPORT GostEngineConfig DESTINATION share/cmake/GostEngine)

Correct CMake files installation path

---

gost12sum.c
test_digest.c
test_tls.c

Infer выдаёт четыре замечания к коду, все несущественные, три точно ложно положительные. На случай, если будет желание включить статический анализ в тесты, я все четыре починил.
```
$ infer run --compilation-database build/compile_commands.json
Capturing using compilation database...
Starting translating 53 files
53/53 [##############################################################################] 100% 5.34s
Found 53 source files to analyze in /home/s/src/crypto/engine/infer-out
Skipped large procedure (__infer_globals_initializer_grasshopper_pil_enc128, size:65543) in pulse.
Skipped large procedure (__infer_globals_initializer_grasshopper_pil_dec128, size:65543) in pulse.
Skipped large procedure (__infer_globals_initializer_grasshopper_l_dec128, size:65543) in pulse.
1161/1161 …
```

Fix static analysis (Infer) complains
