gost-engine/engine

- README.gost
README.gost: Abstract rewritten, outdated text at the end of file is removed
> README.gost: Abstract rewritten, outdated text at the end of file is removed                        

- README.md
Currenty relevant mailing list link is hidden in wiki page with obsure name.
Add the link to ML to README.md file.
> Add mailing list information to README.md

- .ci/build-check.sh
- .ci/build-openssl.sh
- .travis.yml
это позволит детектить ошибки типа https://github.com/gost-engine/engine/issues/55
> initial travis-ci support

- gost_eng.c
- gost_grasshopper_cipher.c
- gost_grasshopper_cipher.h
Ensure the grasshopper ciphers are destroyed on engine destroy.
> Fix a mem leak

- CMakeLists.txt
- gost_grasshopper_cipher.c
- test_context.c
- test_grasshopper.c
Тесты для in-place шифрования. А также фикс обнаруженной ими проблемы с cbc decryption.
> In-place encryption tests and fixes

- test_context.c
Самое главное забыл, чтоб результат тестов влиял на exit code теста.
> test_context: make tests return values affect overall test result

- .travis.yml
Do shallow clone of openssl, make parallel on all available cpus (2).
> travis: speed up Travis build

- .travis.yml
- CMakeLists.txt
Experimental ASan build. Посмотрим что будет.
> travis: Enable ASan build

- CMakeLists.txt
- test_tls.c
Generate cert for every parameter, set it up on s_server, connect s_client, and transfer 1M of data to both directions.
Простой тест, потом можно что-нибудь добавить.
> test_tls: simple TLS connection testing

- CMakeLists.txt
- gosthash2012.c
- test_digest.c
- test_digest: simple digest tests (tested to fail on MIPSel)
- Fix Streebog alignment problem (tested on MIPSel)
> test_digest and alignment fix for Streebog

- test_tls.c
One second was not enough for emulators.
Может быть пофиксит #134.
> test_tls: add more time for the network test

- .cirrus.yml
добрый день!
надо в https://github.com/marketplace выбрать приложение "cirrus-ci"
спасибо!
> initial cirrus-ci support

- CMakeLists.txt
> Fix MacOS building (openssl_1_1_0 branch)

- CMakeLists.txt
> Fix MacOS building (master branch)

- .travis.yml
у coverity время от времени бывает даунтайм. пусть сканы выполняются в отдельном билде раз в сутки
> travis-ci: run coverity scan in separate cron task

- .travis.yml
also, remove deprecated "sudo" key
> travis-ci: add PR testing for OpenSSL-1.1.1 branch

- CMakeLists.txt
Небольшие изменения не меняющие сути.
> gosthash2012: Clean up cmake test for _addcarry_u64

- test_digest.c
There need to be more tests than 2 constant fixed size blocks.
Final digest values are generated from the first run.
Test description in comments, quoted here:
```
/*
* For 256-byte buffer filled with 256 bytes from 0 to 255;
* Digest them 256 times from the buffer end with lengths from 0 to 256,
* and from beginning of the buffer with lengths from 0 to 256;
* Each produced digest is digested again into final sum.
*/
```
> test_digest: Test all block sizes and alignments (Streebog only)

- gost_eng.c
Переделка инициализации на массивы.
> gost_eng: Make it use arrays instead of repeatable code

- test_tls.c
Handle abnormal exit of s_client/s_server processes.
Fixes partially #230.
> test_tls: Introduce timeouts into test to make it not hang

- test_context.c
Also, use testcases table and add more ciphers.
> test_context: Instantiate ciphers using EVP API instead of direct calls

- test_context.c
Test if copying `EVP_MD_CTX' is working good for GOST digests.
Пришлось вернуть `#include "gost_lcl.h"`.
> test_context: Test digests too

- gost_ec_keyx.c
- gost_ec_sign.c
- gost_eng.c
- gost_gost2015.c
- gost_grasshopper_cipher.c
- gost_grasshopper_core.c
- gost_pmeth.c
- gosthash2012.c
- test_gost89.c
- test_keyexpimp.c
All tabs replcaded with spaces. One file was 2 tabs fornating.
> Fix code formating.

- test_tls.c
Also, allow verbose connect setting VERBOSE=1 env var.
> test_tls: Force LEGACY-GOST2012-GOST8912-GOST8912 cipher list

- test_params.c
- test_sign.c
I wanted to test this error https://github.com/openssl/openssl/issues/11861
Also, I found this error https://github.com/openssl/openssl/issues/11870
> Cert/pub_key/priv_key PEM/DER conversion tests

- gost_ec_keyx.c
- test/04-pkey.t
@beldmit I rearranged the logic in the patch to closer match the new description in RFC 7836.
Comments welcome :)
> GOST key agreement cofactor fix

- gost_ec_keyx.c
Update header plate due to significant contributions in #265 (and other).
@bbbrumley @beldmit Do you agree to these lines?
> gost_ec_keyx: Update header plate with copyrights and description

- gost_crypt.c
fix https://github.com/gost-engine/engine/issues/281
> fix gost_cipher_do_cbc multiple blocks decryption is failing

- e_gost_err.c
OpenSSL 3.0 deprecates function codes and ERR_PUT_error() in favor
of ERR_raise() and ERR_set_debug().
> Modernize OpenSSL error reporting

- gost_crypt.c
Fixed bug when acpkm key meshing didn't apply at appropriate time
during TLS secure exchange.
Unify usage of 'num' variable of EVP_CIPHER_CTX for kuznetchik and
magma.
несвоевременно осуществлялась смена ключа в режиме acpkm при шифровании для магмы.
это связанно с тем, что  ф-ии которые используются для шифрования данных для магмы и кузнечика (magma_cipher_do_ctr() и gost_grasshopper_cipher_do_ctracpkm() соответветственно) по разному используют переменную "num" контекста шифрования EVP_CIPHER_CTX.
Так магма в переменной "num" хранит остаток длины зашифрованного сообщения по % block_size (8 - для магмы, 16 - для кузнечика). А длина зашифрованного сообщения в магме хранится в локальном контексте в переменной  "count".
Кузнечик же хранит в "num" длину всего зашифрованного текста и вычисляет …
> update magma cipher ctr_acpkm mode encrypting

- .github/before_script.sh
- .github/script.sh
- .github/workflows/ci.yml
All, excluding ppc64le/s390x/ar64 architectures, macOS,
and Coverity run.
- архитектур нет.
- на macos какие-то ошибки.
- про Coverity не знаю как сделать задание по cronу.
> CI: Covert some Travis-CI to GitHub Actions

- tcl_tests/ca.try
- tcl_tests/cms2.try
- tcl_tests/smime2.try
> We don't want depend on spacing around equal sign

- gost_ameth.c
> Rewrite error handling in pub_decode_gost_ec()

- gost_eng.c
When we use git cli in OS Linux, with enabled gost engine
git utility we got fatal error 
#365
> Use frpintf(stderr, ...) instead of printf(...)

- gost_prov.c
- test/00-provider.t
Output something in `openssl list -providers` so it's merrier.
> Output provider info

- e_gost_err.c
- e_gost_err.h
- gost_ec_keyx.c
Cherry-picking commits from master to fix CVE-2022-29242
> Fix CVE-2022-29242 from master branch

- gost_crypt.c
- gost_grasshopper_cipher.c
- gost_keyexpimp.c
> fixes #438
